if (WIN32)  
    find_program(MAKENSIS_FOUND makensis PATHS "C:/Program Files (x86)/NSIS")
    if (NOT MAKENSIS_FOUND)
        message(STATUS "makensis not found, you can get it here: https://nsis.sourceforge.io")
    else()
        list(APPEND CPACK_GENERATOR   "NSIS")
        set(CPACK_NSIS_PACKAGE_NAME   "${CPACK_PACKAGE_NAME}-${PROJECT_VERSION}")
        set(CPACK_NSIS_CONTACT        "")
        set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)

    endif()
else()
   message(STATUS "Bad cpack type (nsis) for this os (${CMAKE_SYSTEM_NAME})")
endif()
