if (UNIX)
    list(APPEND CPACK_GENERATOR "TGZ")
elseif(WIN32)
    list(APPEND CPACK_GENERATOR "ZIP")
endif()

set(CPACK_ARCHIVE_COMPONENT_INSTALL ON)

set(CPACK_ARCHIVE_COMPONENT_INSTALL  ON)
set(CPACK_ARCHIVE_RUNTIME_FILE_NAME ${CPACK_PACKAGE_NAME})
set(CPACK_ARCHIVE_DEVEL_FILE_NAME   ${CPACK_PACKAGE_NAME}-devel)
set(CPACK_ARCHIVE_DEBUG_FILE_NAME   ${CPACK_PACKAGE_NAME}-debug)

message("------CPACK_PACKAGE_NAME--ARCH------->" ${CPACK_PACKAGE_NAME})
message("------CPACK_ARCHIVE_RUNTIME_FILE_NAME--ARCH------->" ${CPACK_ARCHIVE_RUNTIME_FILE_NAME})
message("------CPACK_ARCHIVE_DEVEL_FILE_NAME--ARCH------->" ${CPACK_ARCHIVE_DEVEL_FILE_NAME})
message("------CPACK_ARCHIVE_DEBUG_FILE_NAME--ARCH------->" ${CPACK_ARCHIVE_DEBUG_FILE_NAME})

